---

# Copyright 2019 Nokia

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Deactivate ipmi sol
  command: "/usr/bin/ipmitool -I lanplus -H {{hosts[ironic_node_details.name]['hwmgmt']['address']}} -U {{hosts[ironic_node_details.name]['hwmgmt']['user']}} -P {{hosts[ironic_node_details.name]['hwmgmt']['password']}} sol deactivate"
  ignore_errors: yes
  no_log: True

- name: Disable shellinabox console logging for target nodes
  environment:
    OS_AUTH_TOKEN: "fake-token"
    IRONIC_URL: "{{ ironic_service_adminurl }}"
  command: "ironic node-set-console-mode {{ironic_node_details.name}} false"
  when:
    - installation_phase == "provisioning-started"

- name: Disable shellinabox console logging for target nodes
  command: "openstack --os-cloud default baremetal node console disable {{ironic_node_details.name}}"
  when:
    - installation_phase != "provisioning-started"

- name: Create directories for tmux
  file:
    path: "{{item}}"
    state: directory
    mode: u=rwx,g=rwx,o=rwx
  with_items:
    - "/var/log/ironic/console_logs"
    - "/tmp/tmp_console"

- name: Start tmux console session
  shell: "source /opt/tmux_setup/tmux.inc; tmux_session_start bash /bin/bash"

- name: Start tmux windows for each nodes
  shell: "source /opt/tmux_setup/tmux.inc; tmux_cmd {{ironic_node_details.name}} /usr/bin/ipmitool -I lanplus -H {{hosts[ironic_node_details.name]['hwmgmt']['address']}} -U {{hosts[ironic_node_details.name]['hwmgmt']['user']}} -P {{hosts[ironic_node_details.name]['hwmgmt']['password']}} sol activate"
  no_log: True
